# copy/paste

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"

# http://stackoverflow.com/a/39741226

set -g default-shell $SHELL
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
